### ISSUE TITLE
Cannot build using Latest release 3.0.3

### ISSUE THREAD

**Issue by samhobeika** [PerfectlySoft/Perfect-RequestLogger#6]
In PerfectRequestLogger, the latest changes made to lines 59-62 cause a compile-time issue

```
let sequence: UInt = queue.sync {
			self.sequence &+= 1
			return self.sequence
		}
```

I think this should be ```self.sequence += 1```

Thanks

**Comment by kjessup** [comment]
Should be fixed in 3.0.4.
